### ISSUE TITLE
Add News 18, Aasirvadham, Maadha Tv

### ISSUE THREAD

**Issue by prabhacap** [echakkara/pvr#1]
https://news18tamil-lh.akamaihd.net/i/n18tamil_1@526595/index_5_av-p.m3u8

http://103.109.45.5:1935/madhatv/madhatv.stream_HDp/chunklist_w67072347.m3u8

http://199.168.96.106:1935/blessingtv-tamillive/mystream/chunklist_w365086533.m3u8

**Comment by echakkara** [comment]
Updated playlist to resolve
